# Generated by Django 5.1.3 on 2024-11-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_access', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmain',
            old_name='product_name',
            new_name='product',
        ),
    ]
